# -*- coding: utf-8 -*-

# baseManager implementation generated from reading ui file 'baseManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from email.mime import base
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
import EquipBase, UseBase, EtcBase
import alertBox

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"
transparent = "background-color: rgba(255, 255, 255, 0);"
_translate = QtCore.QCoreApplication.translate

ADD_BUTTON = -2
VIEW_BUTTON = -3
UPDATE_BUTTON = -4
DELETE_BUTTON = -5

class Ui_baseManager(object):

    def setupUi(self, baseManager):
        
        baseManager.setObjectName("baseManager")
        baseManager.resize(442, 351)
        baseManager.setMinimumSize(QtCore.QSize(442, 351))
        baseManager.setMaximumSize(QtCore.QSize(442, 351))
        baseManager.setStyleSheet(white_background)
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        baseManager.setWindowIcon(icon)
        baseManager.setWindowTitle(_translate("baseManager", "Maplestory Manager - Item Bases"))

        self.gridEquipLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridEquipLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridEquipLayoutWidget.setObjectName("gridEquipLayoutWidget")
        self.gridEquipLayoutWidget.hide()

        self.gridUseLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridUseLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridUseLayoutWidget.setObjectName("gridUseLayoutWidget")
        self.gridUseLayoutWidget.hide()

        self.gridEtcLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridEtcLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridEtcLayoutWidget.setObjectName("gridEtcLayoutWidget")
        self.gridEtcLayoutWidget.hide()

        self.baseSelector = QtWidgets.QComboBox(baseManager)
        self.baseSelector.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.baseSelector.setStyleSheet(grey_background)
        self.baseSelector.setObjectName("baseSelector")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.setItemText(0, _translate("baseManager", "Choose:"))
        self.baseSelector.setItemText(1, _translate("baseManager", "Equip Base"))
        self.baseSelector.setItemText(2, _translate("baseManager", "Use Base"))
        self.baseSelector.setItemText(3, _translate("baseManager", "Etc Base"))
        self.baseSelector.currentTextChanged.connect(lambda: self.changeScreen(self.baseSelector.currentText()))

        self.createRadioButton = QtWidgets.QRadioButton(baseManager)
        self.createRadioButton.setGeometry(QtCore.QRect(100, 10, 71, 17))
        self.createRadioButton.setStyleSheet(transparent)
        self.createRadioButton.setObjectName("createRadioButton")
        self.createRadioButton.setText(_translate("baseManager", "Add Item"))

        self.readRadioButton = QtWidgets.QRadioButton(baseManager)
        self.readRadioButton.setGeometry(QtCore.QRect(180, 10, 71, 17))
        self.readRadioButton.setObjectName("readRadioButton")
        self.readRadioButton.setStyleSheet(transparent)
        self.readRadioButton.setText(_translate("baseManager", "View Item"))

        self.updateRadioButton = QtWidgets.QRadioButton(baseManager)
        self.updateRadioButton.setGeometry(QtCore.QRect(260, 10, 81, 17))
        self.updateRadioButton.setObjectName("updateRadioButton")
        self.updateRadioButton.setText(_translate("baseManager", "Update Item"))

        self.deleteRadioButton = QtWidgets.QRadioButton(baseManager)
        self.deleteRadioButton.setGeometry(QtCore.QRect(350, 10, 81, 17))
        self.deleteRadioButton.setObjectName("deleteRadioButton")
        self.deleteRadioButton.setText(_translate("baseManager", "Delete Item"))

        self.buttonGroup = QtWidgets.QButtonGroup()
        self.buttonGroup.addButton(self.createRadioButton)
        self.buttonGroup.addButton(self.readRadioButton)
        self.buttonGroup.addButton(self.updateRadioButton)
        self.buttonGroup.addButton(self.deleteRadioButton)

        self.output = QtWidgets.QTableWidget(baseManager)
        self.output.setGeometry(QtCore.QRect(180, 40, 241, 301))
        self.output.setObjectName("output")

        self.equipBaseManager(baseManager)
        self.useBaseManager(baseManager)
        self.etcBaseManager(baseManager)

        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def changeScreen(self, text):
        if text == "Equip Base":
            self.gridEquipLayoutWidget.show()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.hide()
            self.updateTable("Equip")
        elif text == "Use Base":
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.show()
            self.gridEtcLayoutWidget.hide()
            self.updateTable("Use")
        elif text == "Etc Base":
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.show()
            self.updateTable("Etc")
        else:
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.hide()

    def updateTable(self, typeOfView): #Para a versao final, colocar os outputs dentro dos Widgets pra não trocar toda hora
        if (typeOfView == "Equip"):
            self.output.setColumnCount(8)
            column1 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(0, column1)
            column2 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(1, column2)
            column3 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(2, column3)
            column4 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(3, column4)
            column5 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(4, column5)
            column6 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(5, column6)
            column7 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(6, column7)
            column8 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(7, column8)

            column1 = self.output.horizontalHeaderItem(0)
            column1.setText(QtCore.QCoreApplication.translate("baseManager", "Equip ID"))
            column2 = self.output.horizontalHeaderItem(1)
            column2.setText(QtCore.QCoreApplication.translate("baseManager", "Equip Name"))
            column3 = self.output.horizontalHeaderItem(2)
            column3.setText(QtCore.QCoreApplication.translate("baseManager", "Class"))
            column4 = self.output.horizontalHeaderItem(3)
            column4.setText(QtCore.QCoreApplication.translate("baseManager", "ATT"))
            column5 = self.output.horizontalHeaderItem(4)
            column5.setText(QtCore.QCoreApplication.translate("baseManager", "MATT"))
            column6 = self.output.horizontalHeaderItem(5)
            column6.setText(QtCore.QCoreApplication.translate("baseManager", "Attribute"))
            column7 = self.output.horizontalHeaderItem(6)
            column7.setText(QtCore.QCoreApplication.translate("baseManager", "Attribute Bonus"))
            column8 = self.output.horizontalHeaderItem(7)
            column8.setText(QtCore.QCoreApplication.translate("baseManager", "Value"))

        elif (typeOfView == "Use"):
            self.output.setColumnCount(6)
            column1 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(0, column1)
            column2 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(1, column2)
            column3 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(2, column3)
            column4 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(3, column4)
            column5 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(4, column5)
            column6 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(5, column6)

            column1 = self.output.horizontalHeaderItem(0)
            column1.setText(QtCore.QCoreApplication.translate("baseManager", "Use ID"))
            column2 = self.output.horizontalHeaderItem(1)
            column2.setText(QtCore.QCoreApplication.translate("baseManager", "Use Name"))
            column3 = self.output.horizontalHeaderItem(2)
            column3.setText(QtCore.QCoreApplication.translate("baseManager", "+HP"))
            column4 = self.output.horizontalHeaderItem(3)
            column4.setText(QtCore.QCoreApplication.translate("baseManager", "+MP"))
            column5 = self.output.horizontalHeaderItem(4)
            column5.setText(QtCore.QCoreApplication.translate("baseManager", "Attribute Bonus"))
            column6 = self.output.horizontalHeaderItem(5)
            column6.setText(QtCore.QCoreApplication.translate("baseManager", "Value"))

        elif (typeOfView == "Etc"):
            self.output.setColumnCount(3)
            column1 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(0, column1)
            column2 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(1, column2)
            column3 = QtWidgets.QTableWidgetItem()
            self.output.setHorizontalHeaderItem(2, column3)

            column1 = self.output.horizontalHeaderItem(0)
            column1.setText(QtCore.QCoreApplication.translate("baseManager", "Etc ID"))
            column2 = self.output.horizontalHeaderItem(1)
            column2.setText(QtCore.QCoreApplication.translate("baseManager", "Etc Name"))
            column3 = self.output.horizontalHeaderItem(2)
            column3.setText(QtCore.QCoreApplication.translate("baseManager", "Value"))


    def equipBaseManager(self, baseManager):
        self.gridLayoutEquip = QtWidgets.QGridLayout(self.gridEquipLayoutWidget)
        self.gridLayoutEquip.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEquip.setObjectName("gridLayoutEquip")

        self.attLabel = QtWidgets.QLabel(self.gridEquipLayoutWidget)
        self.attLabel.setObjectName("attLabel")
        self.gridLayoutEquip.addWidget(self.attLabel, 3, 0, 1, 1)

        self.attackPower = QtWidgets.QSpinBox(self.gridEquipLayoutWidget)
        self.attackPower.setMaximum(255)
        self.attackPower.setObjectName("attackPower")
        self.gridLayoutEquip.addWidget(self.attackPower, 3, 1, 1, 1)

        self.mattLabel = QtWidgets.QLabel(self.gridEquipLayoutWidget)
        self.mattLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mattLabel.setObjectName("mattLabel")
        self.gridLayoutEquip.addWidget(self.mattLabel, 4, 0, 1, 1)

        self.magicPower = QtWidgets.QSpinBox(self.gridEquipLayoutWidget)
        self.magicPower.setMaximum(255)
        self.magicPower.setObjectName("magicPower")
        self.gridLayoutEquip.addWidget(self.magicPower, 4, 1, 1, 1)

        self.idEquip = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.idEquip.setText("")
        self.idEquip.setObjectName("idEquip")
        self.gridLayoutEquip.addWidget(self.idEquip, 0, 0, 1, 2)

        self.equipName = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.equipName.setText("")
        self.equipName.setObjectName("equipName")
        self.gridLayoutEquip.addWidget(self.equipName, 1, 0, 1, 2)

        self.classCanUse = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.classCanUse.setText("")
        self.classCanUse.setObjectName("classCanUse")
        self.gridLayoutEquip.addWidget(self.classCanUse, 2, 0, 1, 2)

        self.attribute = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.attribute.setText("")
        self.attribute.setObjectName("attribute")
        self.gridLayoutEquip.addWidget(self.attribute, 5, 0, 1, 2)

        self.attributeBonus = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.attributeBonus.setText("")
        self.attributeBonus.setObjectName("attributeBonus")
        self.gridLayoutEquip.addWidget(self.attributeBonus, 6, 0, 1, 2)

        self.okEquipButton = QtWidgets.QPushButton(self.gridEquipLayoutWidget)
        self.okEquipButton.setStyleSheet(grey_background)
        self.okEquipButton.setObjectName("okEquipButton")
        self.gridLayoutEquip.addWidget(self.okEquipButton, 8, 0, 1, 2)
        self.okEquipButton.clicked.connect(lambda: self.parseInformation("Equip"))

        self.equipValue = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.equipValue.setObjectName("equipValue")
        self.gridLayoutEquip.addWidget(self.equipValue, 7, 0, 1, 2)

        self.retranslateUiEquip()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def useBaseManager(self, baseManager):
        self.gridLayoutUse = QtWidgets.QGridLayout(self.gridUseLayoutWidget)
        self.gridLayoutUse.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutUse.setObjectName("gridLayoutUse")

        self.recoveredMP = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.recoveredMP.setText("")
        self.recoveredMP.setObjectName("recoveredMP")
        self.gridLayoutUse.addWidget(self.recoveredMP, 3, 0, 1, 2)

        self.recoveredHP = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.recoveredHP.setText("")
        self.recoveredHP.setObjectName("recoveredHP")
        self.gridLayoutUse.addWidget(self.recoveredHP, 2, 0, 1, 2)

        self.bonusLabel = QtWidgets.QLabel(self.gridUseLayoutWidget)
        self.bonusLabel.setObjectName("bonusLabel")
        self.gridLayoutUse.addWidget(self.bonusLabel, 4, 0, 1, 1)

        self.useValue = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.useValue.setText("")
        self.useValue.setObjectName("useValue")
        self.gridLayoutUse.addWidget(self.useValue, 6, 0, 1, 2)

        self.idUse = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.idUse.setText("")
        self.idUse.setObjectName("idUse")
        self.gridLayoutUse.addWidget(self.idUse, 0, 0, 1, 2)

        self.useName = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.useName.setText("")
        self.useName.setObjectName("useName")
        self.gridLayoutUse.addWidget(self.useName, 1, 0, 1, 2)

        self.okUseButton = QtWidgets.QPushButton(self.gridUseLayoutWidget)
        self.okUseButton.setStyleSheet(grey_background)
        self.okUseButton.setObjectName("okUseButton")
        self.gridLayoutUse.addWidget(self.okUseButton, 7, 0, 1, 2)
        self.okUseButton.clicked.connect(lambda: self.parseInformation("Use"))

        self.attributeBonusUse = QtWidgets.QSpinBox(self.gridUseLayoutWidget)
        self.attributeBonusUse.setMinimum(-128)
        self.attributeBonusUse.setMaximum(127)
        self.attributeBonusUse.setObjectName("attributeBonus")
        self.gridLayoutUse.addWidget(self.attributeBonusUse, 4, 1, 1, 1)

        self.retranslateUiUse()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def etcBaseManager(self, baseManager):
        self.gridLayoutEtc = QtWidgets.QGridLayout(self.gridEtcLayoutWidget)
        self.gridLayoutEtc.setContentsMargins(0, 0, 0, 85)
        self.gridLayoutEtc.setObjectName("gridLayoutEtc")

        self.idEtc = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.idEtc.setText("")
        self.idEtc.setObjectName("idEtc")
        self.gridLayoutEtc.addWidget(self.idEtc, 0, 0, 1, 2)

        self.etcName = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.etcName.setText("")
        self.etcName.setObjectName("etcName")
        self.gridLayoutEtc.addWidget(self.etcName, 1, 0, 1, 2)

        self.etcValue = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.etcValue.setText("")
        self.etcValue.setObjectName("etcValue")
        self.gridLayoutEtc.addWidget(self.etcValue, 2, 0, 1, 2)

        self.okEtcButton = QtWidgets.QPushButton(self.gridEtcLayoutWidget)
        self.okEtcButton.setStyleSheet(grey_background)
        self.okEtcButton.setObjectName("okEtcButton")
        self.gridLayoutEtc.addWidget(self.okEtcButton, 3, 0, 1, 2)
        self.okEtcButton.clicked.connect(lambda: self.parseInformation("Etc"))

        self.retranslateUiEtc()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def retranslateUiEquip(self):
        self.idEquip.setPlaceholderText(_translate("baseManager", "Equip ID"))
        self.classCanUse.setPlaceholderText(_translate("baseManager", "Class"))
        self.okEquipButton.setText(_translate("baseManager", "OK"))
        self.equipName.setPlaceholderText(_translate("baseManager", "Equip Name"))
        self.attLabel.setText(_translate("baseManager", "ATT"))
        self.mattLabel.setText(_translate("baseManager", "MATT"))
        self.attribute.setPlaceholderText(_translate("baseManager", "Attribute"))
        self.attributeBonus.setPlaceholderText(_translate("baseManager", "Attribute Bonus"))
        self.equipValue.setPlaceholderText(_translate("baseManager", "Value"))

    def retranslateUiUse(self):
        _translate = QtCore.QCoreApplication.translate
        self.recoveredMP.setPlaceholderText(_translate("baseManager", "Recovered MP"))
        self.recoveredHP.setPlaceholderText(_translate("baseManager", "Recovered HP"))
        self.bonusLabel.setText(_translate("baseManager", "Bonus"))
        self.useValue.setPlaceholderText(_translate("baseManager", "Value"))
        self.idUse.setPlaceholderText(_translate("baseManager", "Use ID"))
        self.useName.setPlaceholderText(_translate("baseManager", "Use Name"))
        self.okUseButton.setText(_translate("baseManager", "OK"))

    def retranslateUiEtc(self):
        _translate = QtCore.QCoreApplication.translate
        self.idEtc.setPlaceholderText(_translate("baseManager", "Etc ID"))
        self.etcName.setPlaceholderText(_translate("baseManager", "Etc Name"))
        self.etcValue.setPlaceholderText(_translate("baseManager", "Value"))
        self.okEtcButton.setText(_translate("baseManager", "OK"))

    def parseInformation(self, base):
        action = self.buttonGroup.checkedId()
        if (base == "Equip"):
            tempIDEquip = self.idEquip.text()
            tempEquipName = self.useName.text()
            tempClass = self.classCanUse.text()
            tempATT = self.attackPower.text()
            tempMATT = self.magicPower.text()
            tempAttribute = self.attribute.text()
            tempBonus = self.attributeBonus.text()
            tempEquipValue = self.useValue.text()

            try:
                if (action == ADD_BUTTON):
                    EquipBase.insert(tempIDEquip, tempEquipName, tempClass, tempATT, tempMATT, tempAttribute, tempBonus, tempEquipValue)

                elif (action == VIEW_BUTTON):
                    if (tempIDEquip == ''):
                        result = EquipBase.selectAll()
                    else:
                        result = EquipBase.select(tempIDEquip)
                        result = [result]
                    self.output.setRowCount(len(result))
                    for i in range(len(result)):
                        for j in range(0,8):
                            self.output.setItem(i, j, QtWidgets.QTableWidgetItem(str(result[i][j])))


                elif (action == UPDATE_BUTTON):
                    EquipBase.update(tempIDEquip, tempEquipName, tempClass, tempATT, tempMATT, tempAttribute, tempBonus, tempEquipValue)

                elif (action == DELETE_BUTTON):
                    EquipBase.delete(tempIDEquip)

            except Exception as e:
                if (type(e) != TypeError):
                    alertBox.AlertBox(e)

        elif (base == "Use"):
            tempIDUse = self.idUse.text()
            tempUseName = self.useName.text()
            tempRecHP = self.recoveredHP.text()
            tempRecMP = self.recoveredMP.text()
            tempBonus = self.attributeBonusUse.text()
            tempUseValue = self.useValue.text()

            try:
                if (action == ADD_BUTTON):
                    UseBase.insert(tempIDUse, tempUseName, tempRecHP, tempRecMP, tempBonus, tempUseValue)
            
                elif (action == VIEW_BUTTON):
                    if (not tempIDUse):
                        result = UseBase.selectAll()
                    else:
                        result = UseBase.select(tempIDUse)
                        result = [result]
                    self.output.setRowCount(len(result))
                    for i in range(len(result)):
                        for j in range(0,6):
                            self.output.setItem(i, j, QtWidgets.QTableWidgetItem(str(result[i][j])))

                elif (action == UPDATE_BUTTON):
                    UseBase.update(tempIDUse, tempUseName, tempRecHP, tempRecMP, tempBonus, tempUseValue)

                elif (action == DELETE_BUTTON):
                    UseBase.delete(tempIDUse)

            except Exception as e:
                if (type(e) != TypeError):
                    alertBox.AlertBox(e)

        else:
            tempIDEtc = self.idEtc.text()
            tempEtcName = self.etcName.text()
            tempEtcValue = self.etcValue.text()
            
            try:
                if (action == ADD_BUTTON):
                    EtcBase.insert(tempIDEtc, tempEtcName, tempEtcValue)

                elif (action == VIEW_BUTTON):
                    if (not tempIDEtc):
                        result = EtcBase.selectAll()
                    else:
                        result = EtcBase.select(tempIDEtc)
                        result = [result]
                    self.output.setRowCount(len(result))
                    for i in range(len(result)):
                        for j in range(0,3):
                            self.output.setItem(i, j, QtWidgets.QTableWidgetItem(str(result[i][j])))

                elif (action == UPDATE_BUTTON):
                    EtcBase.update(tempIDEtc, tempEtcName, tempEtcValue)

                elif (action == DELETE_BUTTON):
                    EtcBase.delete(tempIDEtc)

            except Exception as e:
                if (type(e) != TypeError):
                    alertBox.AlertBox(e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    baseManager = QtWidgets.QWidget()
    ui = Ui_baseManager()
    ui.setupUi(baseManager)
    baseManager.show()
    sys.exit(app.exec_())