# -*- coding: utf-8 -*-

# baseManager implementation generated from reading ui file 'baseManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from email.mime import base
import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"
transparent = "background-color: rgba(255, 255, 255, 0);"
_translate = QtCore.QCoreApplication.translate

class Ui_baseManager(object):

    def setupUi(self, baseManager):
        
        baseManager.setObjectName("baseManager")
        baseManager.resize(442, 351)
        baseManager.setMinimumSize(QtCore.QSize(442, 351))
        baseManager.setMaximumSize(QtCore.QSize(442, 351))
        baseManager.setStyleSheet(white_background)
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        baseManager.setWindowIcon(icon)
        baseManager.setWindowTitle(_translate("baseManager", "Maplestory Manager - Item Bases"))

        self.gridEquipLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridEquipLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridEquipLayoutWidget.setObjectName("gridEquipLayoutWidget")
        self.gridEquipLayoutWidget.hide()

        self.gridUseLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridUseLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridUseLayoutWidget.setObjectName("gridUseLayoutWidget")
        self.gridUseLayoutWidget.hide()

        self.gridEtcLayoutWidget = QtWidgets.QWidget(baseManager)
        self.gridEtcLayoutWidget.setGeometry(QtCore.QRect(10, 40, 131, 311))
        self.gridEtcLayoutWidget.setObjectName("gridEtcLayoutWidget")
        self.gridEtcLayoutWidget.hide()

        self.baseSelector = QtWidgets.QComboBox(baseManager)
        self.baseSelector.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.baseSelector.setStyleSheet(grey_background)
        self.baseSelector.setObjectName("baseSelector")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.setItemText(0, _translate("baseManager", "Choose:"))
        self.baseSelector.setItemText(1, _translate("baseManager", "Equip Base"))
        self.baseSelector.setItemText(2, _translate("baseManager", "Use Base"))
        self.baseSelector.setItemText(3, _translate("baseManager", "Etc Base"))
        self.baseSelector.currentTextChanged.connect(lambda: self.changeScreen(self.baseSelector.currentText()))

        self.deleteRadioButton = QtWidgets.QRadioButton(baseManager)
        self.deleteRadioButton.setGeometry(QtCore.QRect(350, 10, 81, 17))
        self.deleteRadioButton.setObjectName("deleteRadioButton")
        self.deleteRadioButton.setText(_translate("baseManager", "Delete Item"))

        self.updateRadioButton = QtWidgets.QRadioButton(baseManager)
        self.updateRadioButton.setGeometry(QtCore.QRect(260, 10, 81, 17))
        self.updateRadioButton.setObjectName("updateRadioButton")
        self.updateRadioButton.setText(_translate("baseManager", "Update Item"))

        self.readRadioButton = QtWidgets.QRadioButton(baseManager)
        self.readRadioButton.setGeometry(QtCore.QRect(180, 10, 71, 17))
        self.readRadioButton.setObjectName("readRadioButton")
        self.readRadioButton.setStyleSheet(transparent)
        self.readRadioButton.setText(_translate("baseManager", "View Item"))

        self.createRadioButton = QtWidgets.QRadioButton(baseManager)
        self.createRadioButton.setGeometry(QtCore.QRect(100, 10, 71, 17))
        self.createRadioButton.setStyleSheet(transparent)
        self.createRadioButton.setObjectName("createRadioButton")
        self.createRadioButton.setText(_translate("baseManager", "Add Item"))

        self.output = QtWidgets.QListView(baseManager)
        self.output.setGeometry(QtCore.QRect(180, 40, 241, 201))
        self.output.setMinimumSize(QtCore.QSize(241, 151))
        self.output.setObjectName("output")

        self.equipBaseManager(baseManager)
        self.useBaseManager(baseManager)
        self.etcBaseManager(baseManager)

        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def changeScreen(self, text):
        if text == "Equip Base":
            self.gridEquipLayoutWidget.show()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.hide()
        elif text == "Use Base":
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.show()
            self.gridEtcLayoutWidget.hide()
        elif text == "Etc Base":
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.show()
        else:
            self.gridEquipLayoutWidget.hide()
            self.gridUseLayoutWidget.hide()
            self.gridEtcLayoutWidget.hide()


    def equipBaseManager(self, baseManager):
        self.gridLayoutEquip = QtWidgets.QGridLayout(self.gridEquipLayoutWidget)
        self.gridLayoutEquip.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEquip.setObjectName("gridLayoutEquip")

        self.attLabel = QtWidgets.QLabel(self.gridEquipLayoutWidget)
        self.attLabel.setObjectName("attLabel")
        self.gridLayoutEquip.addWidget(self.attLabel, 3, 0, 1, 1)

        self.attackPower = QtWidgets.QSpinBox(self.gridEquipLayoutWidget)
        self.attackPower.setMaximum(255)
        self.attackPower.setObjectName("attackPower")
        self.gridLayoutEquip.addWidget(self.attackPower, 3, 1, 1, 1)

        self.mattLabel = QtWidgets.QLabel(self.gridEquipLayoutWidget)
        self.mattLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mattLabel.setObjectName("mattLabel")
        self.gridLayoutEquip.addWidget(self.mattLabel, 4, 0, 1, 1)

        self.magicPower = QtWidgets.QSpinBox(self.gridEquipLayoutWidget)
        self.magicPower.setMaximum(255)
        self.magicPower.setObjectName("magicPower")
        self.gridLayoutEquip.addWidget(self.magicPower, 4, 1, 1, 1)

        self.idEquip = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.idEquip.setText("")
        self.idEquip.setObjectName("idEquip")
        self.gridLayoutEquip.addWidget(self.idEquip, 0, 0, 1, 2)

        self.equipName = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.equipName.setText("")
        self.equipName.setObjectName("equipName")
        self.gridLayoutEquip.addWidget(self.equipName, 1, 0, 1, 2)

        self.classCanUse = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.classCanUse.setText("")
        self.classCanUse.setObjectName("classCanUse")
        self.gridLayoutEquip.addWidget(self.classCanUse, 2, 0, 1, 2)

        self.attribute = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.attribute.setText("")
        self.attribute.setObjectName("attribute")
        self.gridLayoutEquip.addWidget(self.attribute, 5, 0, 1, 2)

        self.attributeBonus = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.attributeBonus.setText("")
        self.attributeBonus.setObjectName("attributeBonus")
        self.gridLayoutEquip.addWidget(self.attributeBonus, 6, 0, 1, 2)

        self.okEquipButton = QtWidgets.QPushButton(self.gridEquipLayoutWidget)
        self.okEquipButton.setStyleSheet(grey_background)
        self.okEquipButton.setObjectName("okEquipButton")
        self.gridLayoutEquip.addWidget(self.okEquipButton, 8, 0, 1, 2)

        self.equipValue = QtWidgets.QLineEdit(self.gridEquipLayoutWidget)
        self.equipValue.setObjectName("equipValue")
        self.gridLayoutEquip.addWidget(self.equipValue, 7, 0, 1, 2)

        self.retranslateUiEquip()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def useBaseManager(self, baseManager):
        self.gridLayoutUse = QtWidgets.QGridLayout(self.gridUseLayoutWidget)
        self.gridLayoutUse.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutUse.setObjectName("gridLayoutUse")

        self.recoveredMP = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.recoveredMP.setText("")
        self.recoveredMP.setObjectName("recoveredMP")
        self.gridLayoutUse.addWidget(self.recoveredMP, 3, 0, 1, 2)

        self.recoveredHP = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.recoveredHP.setText("")
        self.recoveredHP.setObjectName("recoveredHP")
        self.gridLayoutUse.addWidget(self.recoveredHP, 2, 0, 1, 2)

        self.bonusLabel = QtWidgets.QLabel(self.gridUseLayoutWidget)
        self.bonusLabel.setObjectName("bonusLabel")
        self.gridLayoutUse.addWidget(self.bonusLabel, 4, 0, 1, 1)

        self.useValue = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.useValue.setText("")
        self.useValue.setObjectName("useValue")
        self.gridLayoutUse.addWidget(self.useValue, 6, 0, 1, 2)

        self.idUse = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.idUse.setText("")
        self.idUse.setObjectName("idUse")
        self.gridLayoutUse.addWidget(self.idUse, 0, 0, 1, 2)

        self.useName = QtWidgets.QLineEdit(self.gridUseLayoutWidget)
        self.useName.setText("")
        self.useName.setObjectName("useName")
        self.gridLayoutUse.addWidget(self.useName, 1, 0, 1, 2)

        self.okUseButton = QtWidgets.QPushButton(self.gridUseLayoutWidget)
        self.okUseButton.setStyleSheet(grey_background)
        self.okUseButton.setObjectName("okUseButton")
        self.gridLayoutUse.addWidget(self.okUseButton, 7, 0, 1, 2)

        self.attributeBonus = QtWidgets.QSpinBox(self.gridUseLayoutWidget)
        self.attributeBonus.setMinimum(-128)
        self.attributeBonus.setMaximum(127)
        self.attributeBonus.setObjectName("attributeBonus")
        self.gridLayoutUse.addWidget(self.attributeBonus, 4, 1, 1, 1)

        self.retranslateUiUse()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def etcBaseManager(self, baseManager):
        self.gridLayoutEtc = QtWidgets.QGridLayout(self.gridEtcLayoutWidget)
        self.gridLayoutEtc.setContentsMargins(0, 0, 0, 85)
        self.gridLayoutEtc.setObjectName("gridLayoutEtc")

        self.idEtc = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.idEtc.setText("")
        self.idEtc.setObjectName("idEtc")
        self.gridLayoutEtc.addWidget(self.idEtc, 0, 0, 1, 2)

        self.etcName = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.etcName.setText("")
        self.etcName.setObjectName("etcName")
        self.gridLayoutEtc.addWidget(self.etcName, 1, 0, 1, 2)

        self.etcValue = QtWidgets.QLineEdit(self.gridEtcLayoutWidget)
        self.etcValue.setText("")
        self.etcValue.setObjectName("etcValue")
        self.gridLayoutEtc.addWidget(self.etcValue, 2, 0, 1, 2)

        self.okEtcButton = QtWidgets.QPushButton(self.gridEtcLayoutWidget)
        self.okEtcButton.setStyleSheet(grey_background)
        self.okEtcButton.setObjectName("okEtcButton")
        self.gridLayoutEtc.addWidget(self.okEtcButton, 3, 0, 1, 2)

        self.retranslateUiEtc()
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def retranslateUiEquip(self):
        self.idEquip.setPlaceholderText(_translate("baseManager", "Equip ID"))
        self.classCanUse.setPlaceholderText(_translate("baseManager", "Class"))
        self.okEquipButton.setText(_translate("baseManager", "OK"))
        self.equipName.setPlaceholderText(_translate("baseManager", "Equip Name"))
        self.attLabel.setText(_translate("baseManager", "ATT"))
        self.mattLabel.setText(_translate("baseManager", "MATT"))
        self.attribute.setPlaceholderText(_translate("baseManager", "Attribute"))
        self.attributeBonus.setPlaceholderText(_translate("baseManager", "Attribute Bonus"))
        self.equipValue.setPlaceholderText(_translate("baseManager", "Value"))

    def retranslateUiUse(self):
        _translate = QtCore.QCoreApplication.translate
        self.recoveredMP.setPlaceholderText(_translate("baseManager", "Recovered MP"))
        self.recoveredHP.setPlaceholderText(_translate("baseManager", "Recovered HP"))
        self.bonusLabel.setText(_translate("baseManager", "Bonus"))
        self.useValue.setPlaceholderText(_translate("baseManager", "Value"))
        self.idUse.setPlaceholderText(_translate("baseManager", "Use ID"))
        self.useName.setPlaceholderText(_translate("baseManager", "Use Name"))
        self.okUseButton.setText(_translate("baseManager", "OK"))

    def retranslateUiEtc(self):
        _translate = QtCore.QCoreApplication.translate
        self.idEtc.setPlaceholderText(_translate("baseManager", "Etc ID"))
        self.etcName.setPlaceholderText(_translate("baseManager", "Etc Name"))
        self.etcValue.setPlaceholderText(_translate("baseManager", "Value"))
        self.okEtcButton.setText(_translate("baseManager", "OK"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    baseManager = QtWidgets.QWidget()
    ui = Ui_baseManager()
    ui.setupUi(baseManager)
    baseManager.show()
    sys.exit(app.exec_())