# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'characterManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from characterManagerAdvancedView import Ui_characterManagerAdvancedView
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"

class Ui_characterManager(object):
    def setupUi(self, characterManager):
        characterManager.setObjectName("characterManager")
        characterManager.resize(588, 305)
        characterManager.setMinimumSize(QtCore.QSize(588, 305))
        characterManager.setMaximumSize(QtCore.QSize(588, 305))
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        characterManager.setWindowIcon(icon)
        characterManager.setStyleSheet(white_background)

        self.charMP = QtWidgets.QLineEdit(characterManager)
        self.charMP.setGeometry(QtCore.QRect(150, 100, 113, 20))
        self.charMP.setText("")
        self.charMP.setObjectName("charMP")

        self.output = QtWidgets.QListView(characterManager)
        self.output.setGeometry(QtCore.QRect(280, 60, 291, 231))
        self.output.setObjectName("output")

        self.createRadioButton = QtWidgets.QRadioButton(characterManager)
        self.createRadioButton.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.createRadioButton.setObjectName("createRadioButton")

        self.charClass = QtWidgets.QLineEdit(characterManager)
        self.charClass.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.charClass.setText("")
        self.charClass.setObjectName("charClass")

        self.charName = QtWidgets.QLineEdit(characterManager)
        self.charName.setGeometry(QtCore.QRect(20, 60, 113, 20))
        self.charName.setText("")
        self.charName.setObjectName("charName")

        self.charHP = QtWidgets.QLineEdit(characterManager)
        self.charHP.setGeometry(QtCore.QRect(150, 60, 113, 20))
        self.charHP.setText("")
        self.charHP.setObjectName("charHP")

        self.deleteRadioButton = QtWidgets.QRadioButton(characterManager)
        self.deleteRadioButton.setGeometry(QtCore.QRect(470, 20, 101, 17))
        self.deleteRadioButton.setObjectName("deleteRadioButton")

        self.readRadioButton = QtWidgets.QRadioButton(characterManager)
        self.readRadioButton.setGeometry(QtCore.QRect(170, 20, 101, 17))
        self.readRadioButton.setObjectName("readRadioButton")

        self.updateRadioButton = QtWidgets.QRadioButton(characterManager)
        self.updateRadioButton.setGeometry(QtCore.QRect(320, 20, 111, 17))
        self.updateRadioButton.setObjectName("updateRadioButton")

        self.charAttribute = QtWidgets.QComboBox(characterManager)
        self.charAttribute.setGeometry(QtCore.QRect(20, 180, 111, 22))
        self.charAttribute.setStyleSheet(grey_background)
        self.charAttribute.setObjectName("charAttribute")
        self.charAttribute.addItem("")
        self.charAttribute.addItem("")
        self.charAttribute.addItem("")
        self.charAttribute.addItem("")

        self.charLevel = QtWidgets.QSpinBox(characterManager)
        self.charLevel.setGeometry(QtCore.QRect(50, 220, 42, 22))
        self.charLevel.setStyleSheet(grey_background)
        self.charLevel.setMaximum(255)
        self.charLevel.setObjectName("charLevel")

        self.levelLabel = QtWidgets.QLabel(characterManager)
        self.levelLabel.setGeometry(QtCore.QRect(20, 220, 31, 21))
        self.levelLabel.setStyleSheet("background-color: rgb(255, 255, 255, 0);")
        self.levelLabel.setObjectName("levelLabel")

        self.charEXP = QtWidgets.QLineEdit(characterManager)
        self.charEXP.setGeometry(QtCore.QRect(150, 140, 113, 20))
        self.charEXP.setText("")
        self.charEXP.setObjectName("charEXP")

        self.server = QtWidgets.QLineEdit(characterManager)
        self.server.setGeometry(QtCore.QRect(20, 140, 113, 20))
        self.server.setText("")
        self.server.setObjectName("server")

        self.charMap = QtWidgets.QLineEdit(characterManager)
        self.charMap.setGeometry(QtCore.QRect(150, 180, 113, 20))
        self.charMap.setText("")
        self.charMap.setObjectName("charMap")

        self.charInventory = QtWidgets.QLineEdit(characterManager)
        self.charInventory.setGeometry(QtCore.QRect(150, 220, 113, 20))
        self.charInventory.setText("")
        self.charInventory.setObjectName("charInventory")

        self.advancedViewButton = QtWidgets.QPushButton(characterManager)
        self.advancedViewButton.setGeometry(QtCore.QRect(150, 260, 111, 31))
        self.advancedViewButton.setStyleSheet(grey_background)
        self.advancedViewButton.setObjectName("advancedViewButton")
        self.advancedViewButton.clicked.connect(self.callAdvancedView)

        self.okButton = QtWidgets.QPushButton(characterManager)
        self.okButton.setGeometry(QtCore.QRect(20, 260, 111, 31))
        self.okButton.setStyleSheet(grey_background)
        self.okButton.setObjectName("okViewButton")

        self.retranslateUi(characterManager)
        QtCore.QMetaObject.connectSlotsByName(characterManager)

    def retranslateUi(self, characterManager):
        _translate = QtCore.QCoreApplication.translate
        characterManager.setWindowTitle(_translate("characterManager", "Maplestory Manager - Character"))
        self.charMP.setPlaceholderText(_translate("characterManager", "MP"))
        self.createRadioButton.setText(_translate("characterManager", "Add Character"))
        self.advancedViewButton.setText(_translate("characterManager", "Advanced View..."))
        self.charClass.setPlaceholderText(_translate("characterManager", "Character Class"))
        self.charName.setPlaceholderText(_translate("characterManager", "Character Name"))
        self.charHP.setPlaceholderText(_translate("characterManager", "HP"))
        self.deleteRadioButton.setText(_translate("characterManager", "Delete Character"))
        self.readRadioButton.setText(_translate("characterManager", "View Character"))
        self.updateRadioButton.setText(_translate("characterManager", "Update Character"))
        self.charAttribute.setItemText(0, _translate("characterManager", "STR"))
        self.charAttribute.setItemText(1, _translate("characterManager", "DEX"))
        self.charAttribute.setItemText(2, _translate("characterManager", "INT"))
        self.charAttribute.setItemText(3, _translate("characterManager", "LUK"))
        self.levelLabel.setText(_translate("characterManager", "Level"))
        self.charEXP.setPlaceholderText(_translate("characterManager", "EXP"))
        self.server.setPlaceholderText(_translate("characterManager", "Server"))
        self.charMap.setPlaceholderText(_translate("characterManager", "Last Map Visited"))
        self.charInventory.setPlaceholderText(_translate("characterManager", "Inventory ID"))
        self.okButton.setText(_translate("characterManager", "OK"))

    def callAdvancedView(self):
        self.characterManagerAdvancedViewWindow = QtWidgets.QWidget()
        self.ui = Ui_characterManagerAdvancedView()
        self.ui.setupUi(self.characterManagerAdvancedViewWindow)
        self.characterManagerAdvancedViewWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    characterManager = QtWidgets.QWidget()
    ui = Ui_characterManager()
    ui.setupUi(characterManager)
    characterManager.show()
    sys.exit(app.exec_())
