# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
from accountManager import Ui_accountManager

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"

class Ui_mainWindow(object):

    def setupUi(self, mainWindow):

        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(531, 484)
        mainWindow.setMinimumSize(QtCore.QSize(531, 484))
        mainWindow.setMaximumSize(QtCore.QSize(531, 484))
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet(white_background)
        self.centralwidget.setObjectName("centralwidget")

        self.accountButton = QtWidgets.QPushButton(self.centralwidget)
        self.accountButton.setGeometry(QtCore.QRect(30, 270, 121, 61))
        self.accountButton.setStyleSheet(grey_background)
        self.accountButton.setObjectName("accountButton")
        self.accountButton.clicked.connect(lambda: self.clicked(1))

        self.characterButton = QtWidgets.QPushButton(self.centralwidget)
        self.characterButton.setGeometry(QtCore.QRect(200, 270, 121, 61))
        self.characterButton.setStyleSheet(grey_background)
        self.characterButton.setObjectName("characterButton")
        self.characterButton.clicked.connect(lambda: self.clicked(2))

        self.mapButton = QtWidgets.QPushButton(self.centralwidget)
        self.mapButton.setGeometry(QtCore.QRect(370, 270, 121, 61))
        self.mapButton.setStyleSheet(grey_background)
        self.mapButton.setObjectName("mapButton")
        self.mapButton.clicked.connect(lambda: self.clicked(3))

        self.storeButton = QtWidgets.QPushButton(self.centralwidget)
        self.storeButton.setGeometry(QtCore.QRect(370, 370, 121, 61))
        self.storeButton.setStyleSheet(grey_background)
        self.storeButton.setObjectName("storeButton")
        self.storeButton.clicked.connect(lambda: self.clicked(4))

        self.baseButton = QtWidgets.QPushButton(self.centralwidget)
        self.baseButton.setGeometry(QtCore.QRect(30, 370, 121, 61))
        self.baseButton.setStyleSheet(grey_background)
        self.baseButton.setObjectName("baseButton")
        self.baseButton.clicked.connect(lambda: self.clicked(5))

        self.inventoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.inventoryButton.setGeometry(QtCore.QRect(200, 370, 121, 61))
        self.inventoryButton.setStyleSheet(grey_background)
        self.inventoryButton.setObjectName("inventoryButton")
        self.inventoryButton.clicked.connect(lambda: self.clicked(6))

        self.maplestoryLogo = QtWidgets.QLabel(self.centralwidget)
        self.maplestoryLogo.setGeometry(QtCore.QRect(-30, 10, 541, 181))
        self.maplestoryLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.maplestoryLogo.setPixmap(QtGui.QPixmap("images\maplestoryLogo.png"))
        self.maplestoryLogo.setObjectName("maplestoryLogo")

        self.selectFunctionLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectFunctionLabel.setGeometry(QtCore.QRect(170, 210, 191, 41))
        self.selectFunctionLabel.setObjectName("selectFunctionLabel")
        
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Maplestory Manager"))
        self.accountButton.setText(_translate("mainWindow", "Account"))
        self.characterButton.setText(_translate("mainWindow", "Character"))
        self.mapButton.setText(_translate("mainWindow", "Map"))
        self.storeButton.setText(_translate("mainWindow", "Store"))
        self.baseButton.setText(_translate("mainWindow", "Base"))
        self.inventoryButton.setText(_translate("mainWindow", "Inventory"))
        self.selectFunctionLabel.setText(_translate("mainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Select a management option</span></p></body></html>"))

    def callAccountManagement(self):
        self.accountManagerWindow = QtWidgets.QWidget()
        self.ui = Ui_accountManager()
        self.ui.setupUi(self.accountManagerWindow)
        self.accountManagerWindow.show()

    def clicked(self, number):
        _translate = QtCore.QCoreApplication.translate
        if number != 1:
            self.accountButton.setText(_translate("mainWindow", "Clicked Button"))
        else:
            self.callAccountManagement()
            #app = QtWidgets.QApplication(sys.argv)
            #accountManagerWindow = QtWidgets.QWidget()
            #ui = Ui_accountManager()
            #ui.setupUi(accountManagerWindow)
            #accountManagerWindow.show()
            #sys.exit(app.exec_())

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
