# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'storeTransactionManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"

class Ui_transactionManager(object):
    def setupUi(self, transactionManager):
        transactionManager.setObjectName("transactionManager")
        transactionManager.resize(422, 273)
        transactionManager.setMinimumSize(QtCore.QSize(422, 273))
        transactionManager.setMaximumSize(QtCore.QSize(422, 273))
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        transactionManager.setWindowIcon(icon)
        transactionManager.setStyleSheet(white_background)

        self.character = QtWidgets.QLineEdit(transactionManager)
        self.character.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.character.setText("")
        self.character.setObjectName("character")

        self.idItem = QtWidgets.QLineEdit(transactionManager)
        self.idItem.setGeometry(QtCore.QRect(10, 120, 121, 20))
        self.idItem.setText("")
        self.idItem.setObjectName("idItem")

        self.buyProduct = QtWidgets.QRadioButton(transactionManager)
        self.buyProduct.setGeometry(QtCore.QRect(10, 10, 41, 17))
        self.buyProduct.setObjectName("buyProduct")

        self.output = QtWidgets.QListView(transactionManager)
        self.output.setGeometry(QtCore.QRect(150, 10, 261, 251))
        self.output.setMinimumSize(QtCore.QSize(241, 151))
        self.output.setObjectName("output")

        self.sellProduct = QtWidgets.QRadioButton(transactionManager)
        self.sellProduct.setGeometry(QtCore.QRect(90, 10, 41, 17))
        self.sellProduct.setObjectName("sellProduct")

        self.quantity = QtWidgets.QLineEdit(transactionManager)
        self.quantity.setGeometry(QtCore.QRect(10, 160, 121, 20))
        self.quantity.setText("")
        self.quantity.setObjectName("quantity")

        self.okButton = QtWidgets.QPushButton(transactionManager)
        self.okButton.setGeometry(QtCore.QRect(10, 200, 121, 31))
        self.okButton.setStyleSheet(grey_background)
        self.okButton.setObjectName("okButton")

        self.itemType = QtWidgets.QComboBox(transactionManager)
        self.itemType.setGeometry(QtCore.QRect(10, 80, 121, 22))
        self.itemType.setStyleSheet(grey_background)
        self.itemType.setObjectName("itemType")
        self.itemType.addItem("")
        self.itemType.addItem("")
        self.itemType.addItem("")

        self.retranslateUi(transactionManager)
        QtCore.QMetaObject.connectSlotsByName(transactionManager)

    def retranslateUi(self, transactionManager):
        _translate = QtCore.QCoreApplication.translate
        transactionManager.setWindowTitle(_translate("transactionManager", "Maplestory Manager - Store (Transaction)"))
        self.idItem.setPlaceholderText(_translate("transactionManager", "Item ID"))
        self.buyProduct.setText(_translate("transactionManager", "Buy"))
        self.sellProduct.setText(_translate("transactionManager", "Sell"))
        self.quantity.setPlaceholderText(_translate("transactionManager", "Quantity"))
        self.okButton.setText(_translate("transactionManager", "OK"))
        self.character.setPlaceholderText(_translate("transactionManager", "Character (ID or Name)"))
        self.itemType.setItemText(0, _translate("transactionManager", "Equip"))
        self.itemType.setItemText(1, _translate("transactionManager", "Use"))
        self.itemType.setItemText(2, _translate("transactionManager", "Etc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transactionManager = QtWidgets.QWidget()
    ui = Ui_transactionManager()
    ui.setupUi(transactionManager)
    transactionManager.show()
    sys.exit(app.exec_())
