# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'storeManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
from storeTransactionManager import Ui_transactionManager

grey_background = "background-color: rgb(245, 245, 245);"
white_background = "background-color: rgb(255, 255, 255);"

class Ui_storeManager(object):
    def setupUi(self, storeManager):
        storeManager.setObjectName("storeManager")
        storeManager.resize(428, 306)
        icon = QIcon()
        icon.addFile(u"images\maplestoryIcon.ico", QSize(), QIcon.Normal, QIcon.Off)
        storeManager.setWindowIcon(icon)
        storeManager.setStyleSheet(white_background)

        self.idItem = QtWidgets.QLineEdit(storeManager)
        self.idItem.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.idItem.setText("")
        self.idItem.setObjectName("idItem")

        self.value = QtWidgets.QLineEdit(storeManager)
        self.value.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.value.setText("")
        self.value.setObjectName("value")

        self.updateRadioButton = QtWidgets.QRadioButton(storeManager)
        self.updateRadioButton.setGeometry(QtCore.QRect(210, 10, 101, 17))
        self.updateRadioButton.setObjectName("updateRadioButton")

        self.createRadioButton = QtWidgets.QRadioButton(storeManager)
        self.createRadioButton.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.createRadioButton.setObjectName("createRadioButton")

        self.deleteRadioButton = QtWidgets.QRadioButton(storeManager)
        self.deleteRadioButton.setGeometry(QtCore.QRect(320, 10, 101, 17))
        self.deleteRadioButton.setObjectName("deleteRadioButton")

        self.stock = QtWidgets.QLineEdit(storeManager)
        self.stock.setGeometry(QtCore.QRect(10, 120, 121, 20))
        self.stock.setText("")
        self.stock.setObjectName("stock")

        self.okButton = QtWidgets.QPushButton(storeManager)
        self.okButton.setGeometry(QtCore.QRect(10, 160, 121, 31))
        self.okButton.setStyleSheet(grey_background)
        self.okButton.setObjectName("okButton")

        self.output = QtWidgets.QListView(storeManager)
        self.output.setGeometry(QtCore.QRect(150, 40, 261, 251))
        self.output.setMinimumSize(QtCore.QSize(241, 151))
        self.output.setObjectName("output")

        self.readRadioButton = QtWidgets.QRadioButton(storeManager)
        self.readRadioButton.setGeometry(QtCore.QRect(110, 10, 81, 17))
        self.readRadioButton.setObjectName("readRadioButton")

        self.simulateButton = QtWidgets.QPushButton(storeManager)
        self.simulateButton.setGeometry(QtCore.QRect(10, 210, 121, 31))
        self.simulateButton.setStyleSheet(grey_background)
        self.simulateButton.setObjectName("simulateButton")
        self.simulateButton.clicked.connect(lambda: self.callStoreTransaction())

        self.retranslateUi(storeManager)
        QtCore.QMetaObject.connectSlotsByName(storeManager)

    def retranslateUi(self, storeManager):
        _translate = QtCore.QCoreApplication.translate
        storeManager.setWindowTitle(_translate("storeManager", "Maplestory Manager - Store"))
        self.idItem.setPlaceholderText(_translate("storeManager", "Item ID"))
        self.value.setPlaceholderText(_translate("storeManager", "Value"))
        self.updateRadioButton.setText(_translate("storeManager", "Update Product"))
        self.createRadioButton.setText(_translate("storeManager", "Add Product"))
        self.deleteRadioButton.setText(_translate("storeManager", "Delete Product"))
        self.stock.setPlaceholderText(_translate("storeManager", "Stock"))
        self.okButton.setText(_translate("storeManager", "OK"))
        self.readRadioButton.setText(_translate("storeManager", "View Product"))
        self.simulateButton.setText(_translate("storeManager", "Shop Transaction..."))

    def callStoreTransaction(self):
        self.storeTransactionWindow = QtWidgets.QWidget()
        self.ui = Ui_transactionManager()
        self.ui.setupUi(self.storeTransactionWindow)
        self.storeTransactionWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    storeManager = QtWidgets.QWidget()
    ui = Ui_storeManager()
    ui.setupUi(storeManager)
    storeManager.show()
    sys.exit(app.exec_())
