# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baseManager(object):
    def setupUi(self, baseManager):
        baseManager.setObjectName("baseManager")
        baseManager.resize(442, 351)
        baseManager.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.deleteRadioButton = QtWidgets.QRadioButton(baseManager)
        self.deleteRadioButton.setGeometry(QtCore.QRect(350, 10, 81, 17))
        self.deleteRadioButton.setObjectName("deleteRadioButton")
        self.updateRadioButton = QtWidgets.QRadioButton(baseManager)
        self.updateRadioButton.setGeometry(QtCore.QRect(260, 10, 81, 17))
        self.updateRadioButton.setObjectName("updateRadioButton")
        self.readRadioButton = QtWidgets.QRadioButton(baseManager)
        self.readRadioButton.setGeometry(QtCore.QRect(180, 10, 71, 17))
        self.readRadioButton.setObjectName("readRadioButton")
        self.createRadioButton = QtWidgets.QRadioButton(baseManager)
        self.createRadioButton.setGeometry(QtCore.QRect(100, 10, 71, 17))
        self.createRadioButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.createRadioButton.setObjectName("createRadioButton")
        self.okButton = QtWidgets.QPushButton(baseManager)
        self.okButton.setGeometry(QtCore.QRect(10, 310, 111, 31))
        self.okButton.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.okButton.setObjectName("okButton")
        self.output = QtWidgets.QListView(baseManager)
        self.output.setGeometry(QtCore.QRect(180, 40, 241, 201))
        self.output.setMinimumSize(QtCore.QSize(241, 151))
        self.output.setObjectName("output")
        self.baseSelector = QtWidgets.QComboBox(baseManager)
        self.baseSelector.setGeometry(QtCore.QRect(10, 10, 81, 22))
        self.baseSelector.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.baseSelector.setObjectName("baseSelector")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.baseSelector.addItem("")
        self.attackPower = QtWidgets.QSpinBox(baseManager)
        self.attackPower.setGeometry(QtCore.QRect(10, 190, 42, 22))
        self.attackPower.setMaximum(255)
        self.attackPower.setObjectName("attackPower")
        self.magicPower = QtWidgets.QSpinBox(baseManager)
        self.magicPower.setGeometry(QtCore.QRect(70, 190, 42, 22))
        self.magicPower.setMaximum(255)
        self.magicPower.setObjectName("magicPower")
        self.attLabel = QtWidgets.QLabel(baseManager)
        self.attLabel.setGeometry(QtCore.QRect(10, 160, 21, 21))
        self.attLabel.setObjectName("attLabel")
        self.mattLabel = QtWidgets.QLabel(baseManager)
        self.mattLabel.setGeometry(QtCore.QRect(70, 160, 31, 21))
        self.mattLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.mattLabel.setObjectName("mattLabel")
        self.attribute = QtWidgets.QLineEdit(baseManager)
        self.attribute.setGeometry(QtCore.QRect(10, 230, 113, 20))
        self.attribute.setText("")
        self.attribute.setObjectName("attribute")
        self.attributeBonus = QtWidgets.QLineEdit(baseManager)
        self.attributeBonus.setGeometry(QtCore.QRect(10, 270, 113, 20))
        self.attributeBonus.setText("")
        self.attributeBonus.setObjectName("attributeBonus")
        
        self.testButton = QtWidgets.QPushButton(baseManager)
        self.testButton.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.testButton.setText("AAAAAA")
        self.testButton.setObjectName("testButton")
        self.testButton.clicked.connect(lambda: self.cal(baseManager))

        self.verticalLayoutWidget = QtWidgets.QWidget(baseManager)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 250, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        #self.cal(baseManager)

        self.retranslateUi(baseManager)
        QtCore.QMetaObject.connectSlotsByName(baseManager)

    def cal(self, baseManager):
        _translate = QtCore.QCoreApplication.translate
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.idEquip = QtWidgets.QLineEdit(baseManager)
        self.idEquip.setGeometry(QtCore.QRect(270, 270, 113, 20))
        self.idEquip.setText("")
        self.idEquip.setObjectName("idEquip")
        self.idEquip.setPlaceholderText(_translate("baseManager", "Equip ID"))
        self.verticalLayout.addWidget(self.idEquip)
        self.equipName = QtWidgets.QLineEdit(baseManager)
        self.equipName.setGeometry(QtCore.QRect(270, 290, 113, 20))
        self.equipName.setText("")
        self.equipName.setObjectName("equipName")
        self.equipName.setPlaceholderText(_translate("baseManager", "Equip Name"))
        self.verticalLayout.addWidget(self.equipName)
        self.classCanUse = QtWidgets.QLineEdit(baseManager)
        self.classCanUse.setGeometry(QtCore.QRect(270, 310, 113, 20))
        self.classCanUse.setText("")
        self.classCanUse.setObjectName("classCanUse")
        self.classCanUse.setPlaceholderText(_translate("baseManager", "Class"))
        self.verticalLayout.addWidget(self.classCanUse)
        


    def retranslateUi(self, baseManager):
        _translate = QtCore.QCoreApplication.translate
        baseManager.setWindowTitle(_translate("baseManager", "Maplestory Manager - Item Bases"))
        self.deleteRadioButton.setText(_translate("baseManager", "Delete Item"))
        self.updateRadioButton.setText(_translate("baseManager", "Update Item"))
        self.readRadioButton.setText(_translate("baseManager", "View Item"))
        self.createRadioButton.setText(_translate("baseManager", "Add Item"))
        self.okButton.setText(_translate("baseManager", "OK"))
        self.baseSelector.setItemText(0, _translate("baseManager", "Equip Base"))
        self.baseSelector.setItemText(1, _translate("baseManager", "Use Base"))
        self.baseSelector.setItemText(2, _translate("baseManager", "Etc. Base"))
        self.attLabel.setText(_translate("baseManager", "ATT"))
        self.mattLabel.setText(_translate("baseManager", "MATT"))
        self.attribute.setPlaceholderText(_translate("baseManager", "Attribute"))
        self.attributeBonus.setPlaceholderText(_translate("baseManager", "Attribute Bonus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    baseManager = QtWidgets.QWidget()
    ui = Ui_baseManager()
    ui.setupUi(baseManager)
    baseManager.show()
    sys.exit(app.exec_())
