# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

grey_background = "background-color: rgb(245, 245, 245);"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 484)
        MainWindow.setMinimumSize(QtCore.QSize(531, 484))
        MainWindow.setMaximumSize(QtCore.QSize(531, 484))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.accountButton = QtWidgets.QPushButton(self.centralwidget)
        self.accountButton.setGeometry(QtCore.QRect(30, 270, 121, 61))
        self.accountButton.setStyleSheet(grey_background)
        self.accountButton.setObjectName("accountButton")
        self.characterButton = QtWidgets.QPushButton(self.centralwidget)
        self.characterButton.setGeometry(QtCore.QRect(200, 270, 121, 61))
        self.characterButton.setStyleSheet(grey_background)
        self.characterButton.setObjectName("characterButton")
        self.mapButton = QtWidgets.QPushButton(self.centralwidget)
        self.mapButton.setGeometry(QtCore.QRect(370, 270, 121, 61))
        self.mapButton.setStyleSheet(grey_background)
        self.mapButton.setObjectName("mapButton")
        self.storeButton = QtWidgets.QPushButton(self.centralwidget)
        self.storeButton.setGeometry(QtCore.QRect(370, 370, 121, 61))
        self.storeButton.setStyleSheet(grey_background)
        self.storeButton.setObjectName("storeButton")
        self.baseButton = QtWidgets.QPushButton(self.centralwidget)
        self.baseButton.setGeometry(QtCore.QRect(30, 370, 121, 61))
        self.baseButton.setStyleSheet(grey_background)
        self.baseButton.setObjectName("baseButton")
        self.inventoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.inventoryButton.setGeometry(QtCore.QRect(200, 370, 121, 61))
        self.inventoryButton.setStyleSheet(grey_background)
        self.inventoryButton.setObjectName("inventoryButton")
        self.maplestoryLogo = QtWidgets.QLabel(self.centralwidget)
        self.maplestoryLogo.setGeometry(QtCore.QRect(-30, 10, 541, 181))
        self.maplestoryLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.maplestoryLogo.setPixmap(QtGui.QPixmap("../images/maplestoryLogo.png"))
        self.maplestoryLogo.setObjectName("maplestoryLogo")
        self.selectFunctionLabel = QtWidgets.QLabel(self.centralwidget)
        self.selectFunctionLabel.setGeometry(QtCore.QRect(140, 210, 251, 41))
        self.selectFunctionLabel.setObjectName("selectFunctionLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.accountButton.setText(_translate("MainWindow", "Account"))
        self.characterButton.setText(_translate("MainWindow", "Character"))
        self.mapButton.setText(_translate("MainWindow", "Map"))
        self.storeButton.setText(_translate("MainWindow", "Store"))
        self.baseButton.setText(_translate("MainWindow", "Base"))
        self.inventoryButton.setText(_translate("MainWindow", "Inventory"))
        self.selectFunctionLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Selecione a função que deseja utilizar</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
